module.exports = {
  API: {
    pc_web_login: "/pc/web_login",
    pc_web_logout: "/pc/web_logout",
    weixin_config: "/v/course_meta/weixin_index_parameter",
    weixin_upload_img: "",
    gkklist: "/v/gkk/course/course_list",
    course_about: "/v/gkk/course/course_about",
    course_study: "/v/gkk/course/course_study",
    learningplan: "/v/gkk/course/learning_plan_list",
    learning_plan_choose: "/v/gkk/course/learning_plan_choose",
    payment_study_plan: "/v/gkk/course/payment_study_plan",
    learning_status: "/v/gkk/course/learning_status",
    learning_log: "/v/gkk/course/learning_log",
    section_detail: "/v/gkk/course/section_detail",
    learning_section_cards: "/v/gkk/course/learning_section_cards",
    question_count: "/v/gkk/qa/question_count",
    problem_detail: "/v/gkk/course/problem_detail",
    view_record: "/v/gkk/course/view_record",
    section_finish: "/v/gkk/course/section_finish",
    reservation: "/v/gkk/course/reservation",
    course_quality_list: "/v/gkk/course/course_quality_list",
    courseprofile: "/v/gkk/course/course_profile",
    course_learned: "/v/gkk/course/course_learned",
    gkkqas: "/v/gkk/qa/qa_list",
    gkkqa_item: "/v/gkk/qa/question",
    gkkqaitem_star_question: "/v/gkk/qa/collection/add_question",
    gkkqaitem_star_answer: "/v/gkk/qa/collection/add_answer",
    opencourse_ask: "/v/gkk/qa/create_question",
    opencourse_ask_edit: "/v/gkk/qa/edit_question",
    opencourse_qaitem_answer: "/v/gkk/qa/answer",
    gkkqa_item_myanswer: "/v/gkk/qa/my_answer",
    gkk_qaitem_comment_sommeanswer: "/v/gkk/qa/comment",
    gkk_qaitem_comment_delete: "/v/gkk/qa/comment_delete",
    gkk_qaitem_get_comment: "/v/gkk/qa/comments",
    mytickets: "/v/gkk/qa/my_tickets",
    thumbaction: "/v/gkk/qa/action_thumb",
    peekaction: "/v/gkk/qa/see_answer",
    inviteaction: "/v/gkk/qa/invite_answer",
    gkk_qaitem_answer_teacher: "/v/gkk/qa/get_see_answer",
    deleteqaitem: "/v/gkk/qa/delete_qa",
    delete_answeritem: "/v/gkk/qa/delete_answer",
    discover_new: "/v/discover/new",
    discover_mark: "/v/discover/mark",
    collection_list: "/v/course_meta/my_collections",
    deletecollection: "/v/course_meta/delete_collection",
    paper_list: "/v/quiz/my_papers",
    deletepaper: "/v/quiz/delete_paper",
    user_profile: "/v/course_meta/user_info",
    user_profile_edit: "/v/course_meta/edit_user_info",
    school_name_query: "/school_name/school_name_query",
    mycourse: "/v/course_meta/my_courses",
    edit_course: "/v/course_meta/edit_course",
    create_course: "/v/course_meta/create_course",
    exitClassroom: "/course_meta/quit_classroom",
    join_classroom: "/v/course_meta/join_classroom",
    manage_classroom_student: "/v/course_meta/manage_classroom_student",
    manage_classroom_teachinglogs:
      "/v/course_meta/manage_classroom_teachinglogs",
    manage_student: "/v/course_meta/manage_classroom_batchstudent",
    manage_role: "/v/course_meta/manage_role",
    manage_role_collaborator: "/v/course_meta/manage_role_collaborator",
    select_collection: "/v/course_meta/select_collection",
    select_collection2classroom: "/v/course_meta/select_collection2classroom",
    select_paper: "/v/quiz/select_paper",
    select_paper2classroom: "/v/quiz/select_paper2classroom",
    learning_lesson_detail: "/v/lesson/learning_lesson_detail",
    classroom_student_search: "/v/course_meta/classroom_student_search",
    learning_lesson_detail_v2: "/v/lesson/learning_lesson_detail_v2",
    learning_cards_detail: "/v/cards/learning_cards_detail",
    student_ppt: "/v/lesson/show_studentsPPT",
    cards_feedback_reply: "/v/cards/cards_feedback_reply",
    cards_finished_list: "/v/cards/cards_finished_list",
    cards_viewer_list: "/v/cards/cards_viewer_list",
    teaching_cards_detail: "/v/cards/teaching_cards_detail",
    teacher_cards_answer_detail: "/v/cards/teacher_cards_problems_detail",
    teacher_quiz_detail: "/v/quiz/teacher_quiz_detail",
    teacher_quiz_finish_list: "/v/quiz/quiz_finish_list",
    teacher_quiz_checked_detail: "/v/quiz/quiz_checked_detail",
    teacher_quiz_answer_detail: "/v/quiz/teacher_quiz_problems_detail",
    teacher_quiz_score_detail: "/v/quiz/teacher_quiz_score_detail",
    teacher_PPT: "/v/lesson/show_teacherPPT",
    teacher_PPT_one: "/v/lesson/show_teacherslide_info",
    teacher_slideproblem_detail: "/v/lesson/show_teacherslideproblem_detail",
    lesson_subjective_problem_result_list:
      "/v/lesson/subjective_problem_result_list",
    subjective_problem_unfinished_list:
      "/v/lesson/subjective_problem_unfinished_list",
    subjective_problem_teacher_scorev2:
      "/v/lesson/subjective_problem_teacher_scorev2",
    teacher_slideproblem_resultdetail:
      "/v/lesson/show_teacherslideproblem_resultdetail",
    lesson_detail_teacher_presentation:
      "/v/lesson/lesson_detail_teacher_presentation",
    audit_classroom: "/edu_admin/audit_classroom/",
    teaching_lesson_detail: "/v/lesson/teaching_lesson_detail",
    teaching_lesson_detail_additional:
      "/v/lesson/teaching_lesson_detail_additional",
    lesson_problem_statistics: "/v/lesson/lesson_problem_statistics",
    teaching_lesson_rank: "/v/lesson/teaching_lesson_student_score_list",
    teaching_lesson_personal: "/v/lesson/teaching_lesson_student_score_detail",
    random_name_list: "/v/lesson/random_name_list",
    lesson_not_participant_list: "/v/lesson/lesson_not_participant_list",
    teaching_lesson_members: "/v/lesson/teaching_lesson_participant_list",
    teaching_lesson_slides:
      "/v/lesson/teaching_lesson_slides_unknow_count_list",
    teaching_lesson_slide_detail:
      "/v/lesson/teaching_lesson_slide_students_unknow_list",
    teaching_lesson_problems: "/v/lesson/teaching_lesson_problem_list",
    teaching_lesson_problem_detail:
      "/v/lesson/teaching_lesson_problem_students_list",
    get_subj_result_score_detail: "/v/lesson/get_subj_result_score_detail/",
    edit_subj_problem_score_proportion:
      "/v/lesson/edit_subj_problem_score_proportion",
    lesson_danmu_detail: "/v/lesson/danmu_detail",
    mystore: "/v/gkk/collection/mycollection",
    mystore_create_tag: "/v/gkk/collection/create_tag",
    mystore_delete_tag: "/v/gkk/collection/delete_tag",
    mystore_create_tougao_tag: "/v/api/tougao/create_tag",
    mystore_delete_tougao_tag: "/v/api/tougao/delete_tag",
    publish_paper: "/v/quiz/publish_paper2classroom",
    publish_collection: "/v/course_meta/publish_collection2classroom",
    message_task: "/v/gkk/msg/tasks",
    message_notice: "/v/gkk/msg/notifications",
    message_notice_new: "/v/gkk/msg/tasks_and_notifications",
    message_fans: "/v/gkk/msg/follows",
    message_mark: "/v/gkk/msg/mark",
    message_new: "/v/gkk/msg/new",
    bank_balance: "/pay/inner",
    generate_order: "/pay/mp/order",
    bank_query: "/pay/query",
    members_profile: "/api/op/web_get_classroom_members_profile",
    platform_node: "/api/op/node_proxy",
    classroom_students: "/api/op/web_get_classroom_members",
    platform_exp_reminder: "/api/op/exp_reminder",
    pro_getBindSchool: "/edu_admin/get_university_info/",
    bind_user_number: "/edu_admin/bind_user_number/",
    unbind_user_number: "/edu_admin/unbind_user_number/",
    get_verify_info: "/edu_admin/verify/get_verify_basic_info/",
    get_verify_code: "/edu_admin/verify/get_verify_code/",
    get_cas_university_bind_hint: "/edu_admin/get_cas_university_bind_hint/",
    teacher_tougao_list: "/v/api/tougao/teacher/list",
    teacher_tougao_collect: "/v/api/tougao/collect",
    teacher_tougao_collect_cancel: "/v/api/tougao/collect_cancel",
    student_tougao_list: "/v/api/tougao/student/list",
    publish_appointment: "/v/course_meta/publish_appointment/",
    delete_publish_appointment: "/v/course_meta/delete_publish_appointment/",
    edit_publish_appointment: "/v/course_meta/edit_publish_appointment/",
    async_publish_appointment: "/v/course_meta/async_publish_appointment/",
    publish_appointment_schedule:
      "/v/course_meta/publish_appointment_schedule/",
    get_export_activities: "/v/course_meta/get_export_activities/",
    generate_data_export: "/v/course_meta/generate_data_export/",
    query_export_task_state: "/v/course_meta/query_export_task_state/",
    get_event_extra_info: "/api/op/get_event_extra_info?event_id=",
    publish_notice: "/v/link/classroom_info",
    topublish_notice: "/v/link/publish_notice2classroom",
    notice_view: "/v/link/notice_info",
    delete_notice: "/v/link/delete_notice",
    notice_ready_static: "/v/link/notice_view_list",
    edit_user_avatar: "/v/course_meta/edit_user_avatar",
    problemset_course_list: "/v/problem/my_problem_list",
    problemset_course_activities: "/v/problem/all_problem_list",
    problemset_error_problems: "/v/problem/error_problem_list",
    problemset_star_problems: "/v/problem/star_problem_list",
    problemset_cards_problems: "/v/problem/cards_problem_list",
    problemset_lesson_problems: "/v/problem/lesson_problem_list",
    problemset_quiz_problems: "/v/problem/quiz_problem_list",
    problemset_add_star: "/v/problem/add_star",
    problemset_cancel_star: "/v/problem/cancel_star",
    problemset_add_note: "/v/problem/add_modify_note",
    teacher_cards_detail: "/v/cards/cards_detail_teacher_slides/",
    set_lang_en: "/v/user/set_language/en",
    set_lang_zh_cn: "/v/user/set_language/zh_cn",
    get_post: "/v/discussion/one_topic_fetch",
    reply_post: "/v/discussion/reply_create_with_post",
    get_post_comments: "/v/discussion/comment_fetch",
    get_post_comment: "/v/discussion/one_comment_fetch",
    do_digg: "/v/discussion/like_up",
    cancel_digg: "/v/discussion/like_cancel",
    get_digg_list: "/v/discussion/like_user_list",
    del_post: "/v/discussion/topic_delete",
    del_post_reply: "/v/discussion/reply_delete",
    post_dicssuion: "/v/discussion/topic_create",
    discussion_topic_fetch: "/v/discussion/classroom_topic_fetch",
    discussion_like_up: "/v/discussion/like_up",
    discussion_like_cancel: "/v/discussion/like_cancel",
    topic_edit: "/v/discussion/topic_edit",
    activity_topic_create: "/v/discussion/activity_topic_create",
    classroom_logs: "/v/course_meta/classroom_logs",
    manage_teaching_activity: "/v/course_meta/manage_teaching_activity",
    check_permission_manage_teaching_activity:
      "/v/course_meta/check_permission_manage_teaching_activity",
    on_lesson_courses: "/v/course_meta/on_lesson_courses",
    own_collections: "/v/cards/own_collections",
    learned_cards: "/v/cards/learned_cards",
    own_papers: "/v/quiz/own_papers",
    learned_quiz: "/v/quiz/learned_quiz",
    change_directory: "/api/cop/change_directory",
    get_user: "/v/course_meta/fetch_user_info",
    send_letter: "/v/course_meta/send_letter",
    test: "",
    cards_status_list: "/v/cards/cards_status_list",
    student_cards_detail: "/v/cards/student_cards_detail",
    teacher_quiz_result_list: "/v/quiz/teacher_quiz_result_list",
    student_quiz_detail: "/v/quiz/student_quiz_detail",
    get_current_language: "/v/user/get_current_language",
    web_get_event_detail: "/api/op/web_get_event_detail/",
    get_screenshot_list: "/v/lesson/file_sharing/get_lesson_share_list/",
    get_lesson_timeline: "/v/lesson/get_lesson_replay_timeline/",
    get_lesson_info: "/v/lesson/get_lesson_replay_content/",
    get_board_track: "/v/lesson/file_sharing/get_board_track",
    hole_service_notice: "/pc/hole_service_notice/",
    force_bind_status: "/pc/force_bind_status",
    is_bind_phone: "/pc/is_bind_phone",
    bind_phone: "/pc/bind_phone",
    send_sms_code: "/pc/send_sms_code",
    payment_proxy: "/v/payment/node_proxy",
    behavior_tag: {
      student_about: "/v/lesson/behavior_tag/student_about",
      change_participate: "/v/lesson/behavior_tag/change_participate",
      change_score: "/v/lesson/behavior_tag/change_score",
      search_classroom_student:
        "/v/lesson/behavior_tag/search_classroom_student",
      create_tag: "/v/lesson/behavior_tag/created",
      bind_student: "/v/lesson/behavior_tag/bind_student",
      deleted_tag: "/v/lesson/behavior_tag/deleted"
    },
    post_studentlessonslide_tag: "/v/lesson/post_studentlessonslide_tag"
  }
};
